# Generated by Django 2.0 on 2017-12-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('id_cliente', models.BigIntegerField()),
                ('txn', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
