# Generated by Django 2.0 on 2017-12-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_cliente',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
