# Generated by Django 2.0 on 2017-12-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171218_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
